name: Test Automation WorkFlow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework with Maven
      run: mvn test -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload a Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test logs
        path: logs/

    - name: Upload a Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Reports
        path: extent-reports/report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"












    
